### PR TITLE
Command-line arguments system

### PR DESCRIPTION
**Pull request by ghost**
I made a few adjustments to the code, and now it accepts command-line arguments.

It also uses the local path instead of the global path. This means you use `images` and not `X:\SomeUser\SomeFolder\AnotherFolder\images`

Also, there is a progress meter. On my computer, it took a long time to simulate and I got bored, so I added a progress meter and now I can tell how much of it is complete.

### CODE REVIEW

**Comment by ghost** [comment]
I just added support for positional arguments.
The first one is *source folder*, then *speed*, then *extension*, then *width* and then *height*.
I think this should make the console more cleaner.

**Comment by lindhe** [comment]
You have created a really fine parsing of flags and arguments, but I think it's preferable to use argparse or getopt. They have so many minor details fixed regarding parsing the args. Even though I think your code actually looks better than #2, I'd rather see it implemented via argparse.

**Comment by ghost** [comment]
Yes, but in argparse, an argument must be positional or optional. With this approach, arguments are both positional and optional. You use *-p*, *-s*, *-f* etc. if you want to. There's no way you can do that using argparse *(that I'm aware of)*. I'll just try and do that anyways though.

**Comment by ghost** [comment]
Nope. I couldn't make them work both optionally and positionally.

**Comment by lindhe** [comment]
Just pass the correct `nargs`; https://docs.python.org/3.6/library/argparse.html#nargs

Example (I think, just skimmed over it):
https://stackoverflow.com/questions/4480075/argparse-optional-positional-arguments#4480202

**Comment by ghost** [comment]
I am closing this, as there are better options for argument systems.

**Pull request closed without merging**
