### PR TITLE
Added console input to get rid of the need to manually change the var…

### PR DESCRIPTION
**Pull request by Redrield**
…iables of the script

### CODE REVIEW

**Review by jamescmacey — COMMENTED** [review]
Maybe it would be better not to set the default output folder to /Users/mattparker/...... and instead set it to default to the user's desktop/make a new folder in the current directory?

**Comment by bsubei** [comment]
Take a look at [argparse](https://docs.python.org/3/library/argparse.html). Much cleaner way to do this :)

**Comment by Redrield** [comment]
Not really a Python programmer myself, I dabbled with it before but I'm more comfortable with Rust, and lower level things. I'll give it a look when I get a chance.

**Comment by bsubei** [comment]
Interesting, I'm kind of the opposite (comfortable with Python but can't seem to figure out Rust). Take a look at #2, I hope it's clear.

**Comment by Redrield** [comment]
I'll just close and let you take over o/

**Pull request closed without merging**
